# Only build master branch and PRs to master branch
if: branch = master

language: android
sudo: false

env:
  global:
  - secure: sw5+BZqf7awCM2X8w7JbGIaT4J8/ES4fWhoo3qZxCTOdJ4ubfNH/2D/VSRCDMOENgGIgBr0NXeO1wyRvA0PBRut0+44Db+2KLycPA1DFU95rzKA/szfWurkc54rnt1Gw3UXS54hIjz+uDZ0h7SbV+uQiTkTpqQJ0b2LgUFMdiuKTp5dfuZqJTfXp/EJuT+EuJeCXolEBlbtMZLSalDq2TWPjTsg6B/JmREChalUwmyIryZsjS3z5RFy0HX4Fy4ucf9f76AuwSgfabZsa/7+/fYQbLRL9dFiPTY5A3M3fKoZ7j35mhb9KUBQC2kp1M4TyttWXressvHeWUUaLingzNJmW7r0xQrFzNFoyKIIUklvfFR1jU+E0Bl4fQEWghpAw15Xm6jPXRDi46wkg4TfMCi3bkCogCDP9OdnwVBFDcz+mKibkduQ3cCBJhtQX0gdpTnxVsyq6GPHYMEY6Mf9DDF2keH4cJy+ehni/GxinYNxCMB4gDcX+9jB6AY8ShyWtwGqBcb2xahF7/CK00CsAkCmmKO8rUJXuTD11a+RN6zTwFUPAs/btS/47mFtsRNvDTfHIe4/hZwpGCDwUKtYqDFG8uuhWQtuPFtscjRkSU2zPcnmAgcH9s/NkYqYmx2rnSvUbyNvGrY/QfRv+pd0+LFu+XAG4Vir4eVK9fK5wOTk=
  - secure: PKHWXUtajn32/anqhi2fx6PZyBbywHTdVkw1ljoa+kOg+mYPDudDAm0BkDF99G16eTBLHacy6zOks1dJyQih3Rg2Efk3182RZ2a+Fq+0NlQnSdoTYamp/V782ABX9Yvw8YX4Ow2rKHgHaMCCn0qVgZqGdttKDbqBZRRP/f93k88sKWnEAXvWgWRr/CQUixB+Xx8l+sXnAK66JsBl0nBHD0NO/XJpnMNixN1B5/6u2wseHLomOjg16P1dOAFZhXDG7sZYByNRMRgPyW54cl+0RCpIrEmHMv0JSnxFvzcU+D4eTfZ87pr0k3LqotI2QMsD+gZOXaSGRolG1irc9n1m260tc9CezJdvf3eKRm2H12AR1lYp8+gUbt1AZnuAA8WSgntqsyUN+eL8bzK6B3EChR8ffp46gcZWgPJTuXMscFVIv6qtimZypFnGHxwypwj89xTVLQi07tuJO1n4KOTlJKGG34G2WiT5KiBKODARLz4uC2nlODqbbm1oKzNtP/O0LO6VkhR6pXaNTSFKORCcAeeOamb9T90wpzOqtJOpboXy187jC0j+RxkGPKuvIKz+x4v5///Q4I4j+Jsllb3Mm0bWAfPd/A5xHG/u7d44Fs22F9HZNKl6ux4IDUjOGSnUcsMn44cGPy4QNs4Qlgib0FOrwQ+oIpSadoObT4IvTwU=

android:
  components:
  - tools
  - build-tools-28.0.3
  - android-28

before_install:
  - yes | sdkmanager "platforms;android-28"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
  - stage: test
    script:
    - ./gradlew assembleDebug checkstyle lintDebug

  - stage: deploy
    if: branch = master AND type = push
    script:
    - git fetch --unshallow # Build number will be incorrect for shallow copy
    - ./gradlew publishSample
