org.gradle.jvmargs=-Xmx5g -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.javaCompile.suppressSourceTargetDeprecationWarning=true
# Workaround: K2 UAST crashes lint when analyzing .kts build scripts
android.lint.useK2Uast=false
